
vault_addr: "0.0.0.0" 
vault_data_dir: "/opt/vault/data"
vault_node_id: "node1"
vault_address: "{{ vault_addr }}:8200"

vault_api_addr: "http://127.0.0.1:8200"
vault_cluster_addr: "http://127.0.0.1:8201"