---
- name: Deploy HashiCorp Vault with Raft storage
  hosts: server

  vars_files:
    - vars/vault.yaml

  tasks:
    - name: Install HashiCorp Vault
      become: true
      apt:
        name: vault
        state: present

    - name: Create Vault configuration directory
      become: true
      file:
        path: /etc/vault.d
        state: directory

    - name: Create Vault data directory
      become: true
      file:
        path: /opt/vault/data
        state: directory

    - name: Set permissions for Vault data folder
      become: true
      file:
        path: /opt/vault/data
        owner: rafael
        group: rafael
        mode: "0755"
    
    - name: Create Vault configuration file
      become: true
      template:
        src: templates/vault.hcl.j2
        dest: /etc/vault.d/vault.hcl

    - name: Copy Vault service file
      become: true
      copy:
        src: files/vault/vault.service
        dest: /etc/systemd/system/vault.service

    - name: Load Vault service
      become: true
      systemd:
        name: vault.service
        daemon_reload: yes
        state: reloaded
        
    - name: Start Vault service
      become: true
      systemd:
        name: vault.service
        state: started
        enabled: true
        
    - name: Start Vault service
      become: true
      systemd:
        name: vault.service
        state: started
        enabled: true
