
version: '3.3' 

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    ports:
      - 1433:1433
    env_file: .sql.env
    volumes:
      - /opt/sqlserver/data:/var/opt/mssql
    user: "10001:0"  
    command: /bin/bash -c "chown -R 10001:0 /var/opt/mssql && /opt/mssql/bin/sqlservr"

volumes:
  sqlserverdata: